version: 2
updates:
  # Python の依存関係
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "auto"
    groups:
      python-core:
        patterns:
          - "python"
          - "pip"
          - "setuptools"
      python-test:
        patterns:
          - "pytest*"
          - "coverage*"
    versioning-strategy: "increase"
    commit-message:
      prefix: "chore"
      include: "scope"

  # GitHub Actions の更新
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"
