paths-ignore:
  - "**/*.md"
  - "**/test_*.py"
  - "docs/**"
  - ".github/workflows/test-*.yml"

custom-patterns:
  - name: "Private Key Headers"
    pattern: "-----BEGIN (RSA|EC|DSA|OPENSSH) PRIVATE KEY-----"
  - name: "AWS Credentials"
    pattern: "AKIA[0-9A-Z]{16}"
  - name: "Generic API Key"
    pattern: "(?i)(api[_-]?key|apikey|api_secret)[\\s]*[:=][\\s]*[\"']?([a-zA-Z0-9_-]{32,})[\"']?"
  - name: "Database Connection String"
    pattern: "(?i)(postgres|mysql|mongodb|redis)://[^:]+:[^@]+@[^/]+"
  - name: "JWT Token"
    pattern: "eyJ[a-zA-Z0-9_-]+\\.eyJ[a-zA-Z0-9_-]+\\.[a-zA-Z0-9_-]+"
