coverage:
  status:
    project: # リポジトリ全体
      default:
        target: 80 # 目標 80%
        threshold: 2 # ±2% までは CI pass
    patch: # PR 単位
      default:
        target: 80
comment:
  layout: "reach, diff, files"
