repos:
  # ---------- General housekeeping ----------
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
        stages: [pre-commit]
      - id: trailing-whitespace
        stages: [pre-commit]
      - id: check-merge-conflict

  # ---------- Code formatter ----------
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black

  # ---------- Linter ----------
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        args:
          - --fix
          - --exit-zero        # lint だけで失敗させない
        stages: [pre-commit]

  # ---------- YAML linter ----------
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint
        args:
          - -d
          - >
            {extends: default,
             rules: {
               truthy: disable,
               line-length: {max: 120, allow-non-breakable-words: true}
             }}
