[tool.poetry]
name        = "desktop-tutorial"
version     = "0.1.0"
description = ""
authors     = ["Your Name <you@example.com>"]

# --- ここがパッケージ宣言 ---
packages = [
  { include = "desktop_tutorial", from = "src" }
]

[tool.poetry.dependencies]
python  = ">=3.11,<4.0"
pyarrow = "^16"
yfinance = {version = "^0.2.65", extras = ["rapidjson"]}

[tool.poetry.group.dev.dependencies]
black   = "^25.1.0"
pytest  = "^8.2"

[build-system]
requires      = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
