[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "desktop-tutorial"
version = "0.1.0"
requires-python = ">=3.11"

[tool.setuptools.packages.find]
where = ["src"]

[tool.poetry.dependencies]
pyarrow = ">=16,<17"

[tool.poetry.group.dev.dependencies]
black = "^25.1.0"
