[tool.poetry]
name        = "desktop-tutorial"
version     = "0.1.12"                 # ← タグと同期させる場合はここを更新
description = "Sample desktop tutorial: fetch market data and run DCF analyses"
authors     = ["Naoto Suima <you@example.com>"]
license     = "MIT"
readme      = "README.md"

# PyPI ページに表示されるリンク類（任意）
homepage     = "https://github.com/suima-dev/desktop-tutorial"
repository   = "https://github.com/suima-dev/desktop-tutorial"
documentation = "https://github.com/suima-dev/desktop-tutorial#readme"

keywords = ["finance", "yahoo-finance", "tutorial"]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]

# --------------- パッケージ配置 ---------------
packages = [
  { include = "desktop_tutorial", from = "src" }
]

# --------------- ランタイム依存 ---------------
[tool.poetry.dependencies]
python = ">=3.9,<4.0"
pandas = "^2.3.1"
pyarrow = "^16.1"
yfinance = "0.2.33"
python-rapidjson = "^1.21"

[tool.poetry.group.dev.dependencies]
pytest      = "^8.2"
pytest-cov  = "^5.0"
ruff        = "^0.4"
black       = "^24.4"
python-rapidjson = "^1.21"
yamllint    = "^1.37.1"
# yamllint  = "^1.36"   ← 3.9 対応版に固定（必要なら）

[build-system]
requires      = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
