[tool.poetry]
name        = "desktop-tutorial"
version     = "0.1.11"                         # ★ タグと同期
description = "Sample desktop tutorial: fetch market data and run DCF analyses"
authors     = ["Naoto Suima <you@example.com>"]
license     = "MIT"
readme      = "README.md"

# Project links (PyPI UI 左サイドバー)
homepage      = "https://github.com/suima0713/desktop-tutorial"
repository    = "https://github.com/suima0713/desktop-tutorial"
documentation = "https://github.com/suima0713/desktop-tutorial#readme"

keywords = ["finance", "yahoo-finance", "tutorial"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

packages = [
  { include = "desktop_tutorial", from = "src" }
]

[tool.poetry.dependencies]
python   = ">=3.11,<4.0"
pyarrow  = "^16"
yfinance = { version = "^0.2.65", extras = ["rapidjson"] }

[tool.poetry.group.dev.dependencies]
black  = "^25.1.0"
pytest = "^8.2"

[build-system]
requires      = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name     = "pypi-main"
url      = "https://pypi.org/simple"
priority = "primary"          # まず本番 PyPI で解決

[[tool.poetry.source]]
name     = "testpypi"
url      = "https://test.pypi.org/simple"
priority = "supplemental"     # 開発パッケージのみこちらで上書き
