name: Basic Test
on:
  push:
    branches: [feature/composite-actions]
  pull_request:
    branches: [main]

jobs:
  basic-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Test Python
        run: |
          python --version
          pip --version
          echo "✅ Basic test passed!"
