---
name: CI with Composite Actions
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Project
        uses: ./.github/actions/setup-project

      - name: Run tests
        run: |
          echo "Running tests..."
          python --version
          pip list

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Project
        uses: ./.github/actions/setup-project

      - name: Run linters
        run: |
          echo "Running linters..."

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Project
        uses: ./.github/actions/setup-project
        with:
          python-version: '3.10'

      - name: Build package
        run: |
          echo "Building package..."
