---
name: CI Optimized
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Project
        uses: ./.github/actions/setup-project
        with:
          python-version: '3.11'

      - name: Run tests
        run: |
          echo "Running tests..."

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-project
        with:
          python-version: '3.11'

      - name: Run linters
        run: |
          echo "Running linters..."
