name: CI smoke

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  smoke:
    runs-on: windows-latest
    env:
      PYTHONUTF8: "1"
      PYTHONIOENCODING: "utf-8"
    defaults:
      run:
        shell: pwsh

    steps:
      # 1) リポジトリ取得
      - uses: actions/checkout@v4

      # 2) PAT 注入（bash）
      - name: Inject PAT for private git URLs
        shell: bash
        env:
          PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global url."https://${PAT}@github.com/".insteadOf "https://github.com/"
          git config --global --get-regexp url

      # 3) 子プロセスへ gitconfig 継承
      - name: Export global gitconfig path
        shell: bash
        run: echo "GIT_CONFIG_GLOBAL=$HOME/.gitconfig" >> "$GITHUB_ENV"

      # 4) Python セットアップ
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
          cache-dependency-path: |
            **/pyproject.toml
            **/requirements*.txt
          
      # 5) ビルドバックエンド更新
      - name: Upgrade pip & setuptools
        run: python -m pip install -U pip setuptools wheel

      # 6) build.ps1 実行（pip_audit は -r 無しに変更済みか確認）
      - name: Run build.ps1
        run: ./build.ps1
