---
name: Production CI
on:
  push:
    branches: [main, develop, feature/composite-actions]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Python environment
        uses: ./.github/actions/setup-project
        with:
          python-version: '3.11'
      
      - name: Cache dependencies
        uses: ./.github/actions/cache-dependencies
        with:
          cache-key-prefix: 'test'
          python-version: '3.11'
      
      - name: Run tests
        run: |
          echo "🧪 Running tests..."
          python --version
          pip --version
          # pytest tests/ --cov=. --cov-report=xml
          echo "✅ Tests completed"

  lint:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Python environment
        uses: ./.github/actions/setup-project
        with:
          python-version: '3.11'
      
      - name: Run linters
        run: |
          echo "🔍 Running code quality checks..."
          # flake8 .
          # black --check .
          # mypy .
          echo "✅ Code quality checks passed"

  build:
    name: Build Package
    runs-on: ubuntu-latest
    needs: [test, lint]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Python environment
        uses: ./.github/actions/setup-project
        with:
          python-version: '3.11'
      
      - name: Build distribution
        run: |
          echo "📦 Building package..."
          # python setup.py sdist bdist_wheel
          echo "✅ Build completed"
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-packages
          path: dist/
          if-no-files-found: ignore
