name: Publish SBOM on Release

on:
  release:
    types: [published]

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Poetry
        run: |
          pip install poetry
          poetry install --no-interaction

      - name: Generate SBOM
        uses: CycloneDX/gh-action-sbom@v1
        with:
          format: json
          output-filename: sbom-cyclonedx.json

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      - name: Sign SBOM with OIDC
        run: |
          cosign sign-blob --yes \
            --output-signature sbom-cyclonedx.json.sig \
            --output-certificate sbom-cyclonedx.json.crt \
            sbom-cyclonedx.json

      - name: Upload SBOM to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            sbom-cyclonedx.json
            sbom-cyclonedx.json.sig
            sbom-cyclonedx.json.crt
