name: Release

on:
  push:
    tags:
      - "v*.*.*"      # 例: v0.1.3

permissions:
  contents: write     # GitHub Release の作成に必要
  id-token: write     # ★ OIDC 認証に必須

jobs:
  publish:
    environment: release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: pip install poetry

      - name: Build package
        run: poetry build

      - name: Publish to TestPyPI             # ← TOKEN 行は削除
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          packages-dir: dist                 # password: 行は不要

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            dist/*.whl
            dist/*.tar.gz
