---
name: Test Composite Actions
on:
  push:
    branches: [feature/composite-actions]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Test setup-project action
        uses: ./.github/actions/setup-project
        with:
          python-version: '3.11'
      
      - name: Verify Python
        run: |
          python --version
          pip --version
